### ISSUE TITLE
is kNumberColumnsRepeated / number-columns-repeated used when loading document?

### ISSUE THREAD

**Issue by novalisek** [f35f22fan/Ods2#8]
Hi,
I have .ods, it has first 2 cells on the row, which are empty. 
If I do row->GetCell(0)->is_empty() I get true, and row->GetCell(0)->ValueToString() returns ""  that is correct
but row->GetCell(1)->is_empty() returns false, and row->GetCell(1)->ValueToString() returns value of third cell, same as 
row->GetCell(2)->is_empty() returns false, and row->GetCell(2)->ValueToString()  returns value of third cell, which is correct

Row in the .ods/content.xml is defined as 
```
 <table:table-row table:style-name="ro1">
               <table:table-cell table:number-columns-repeated="2" />
               <table:table-cell table:style-name="ce4" office:value-type="date" office:date-value="2021-06-02" calcext:value-type="date">
                  <text:p>02.06.2021</text:p>
               </table:table-cell>
```

Do you use number-columns-repeated property somehow when loading cells? Or just when saving them?

**Comment by f35f22fan** [comment]
Hi, thanks,
I could replicate this bug and so I fixed it, please report if I broke something along the way.

On a somewhat related note, sometime later I'll add another way of getting a certain cell or row because row->GetCell(n) iterates over all row's cells each time from the beginning and that's fine if you only need to fetch one cell, but that's ineffective if you're in a loop trying to fetch all row's cells one by one.

**Comment by novalisek** [comment]
Hi, it seems, that the problem is still there somewhere ... I am getting same results

first 2 cells are empty, but second cell returns value of third cell

**Comment by f35f22fan** [comment]
For me it works fine, the result of TestBug() from examples1.cpp (which generates the XML you posted above) yields:

> [examples1.cc:040 TestBug] Cell 0 is empty: true, ()
[examples1.cc:040 TestBug] Cell 1 is empty: true, ()
[examples1.cc:040 TestBug] Cell 2 is empty: false, (2021-07-01)

which is fine because the first 2 cells (which in XML is one cell with number-columns-repeated=2 which counts as two cells) are empty, and the third one (which in XML is the 2nd one) has a date.

**Comment by novalisek** [comment]
https://easyupload.io/4mf4g2   pw is ods2
try to read value of cells B2 (returns data of C2) and F4 (returns value of G4 even if the cell is not empty (but is same as E4))

**Comment by f35f22fan** [comment]
easyupload says:

> This file is password protected. Please enter the password to start download

**Comment by novalisek** [comment]
pw is `ods2`

**Comment by f35f22fan** [comment]
OK, downloaded.

**Comment by f35f22fan** [comment]
I just tested, works fine: B2 = row 1 col 1, F4 = row 3, col 5 (because indices start at zero):

> [build] examples/app
[examples1.cc:054 PrintValue] Row 1, cell 1 is empty: true, ()
[examples1.cc:054 PrintValue] Row 3, cell 5 is empty: false, (Vogele/Hamm/Wirtgen )

`void PrintValue(ods::Sheet *sheet, const int row_index, const int col_index)
{
	auto *row = sheet->GetRow(row_index);
	CHECK_PTR_VOID(row);
	auto *next = row->GetCell(col_index);
	auto ba = next->ValueToString().toLocal8Bit();
	mtl_info("Row %d, cell %d is empty: %s, (%s)", row_index,
		col_index, next->is_empty() ? "true" : "false", ba.data());
}

void TestDownloadedFile()
{
	auto full_path = "/home/fox/Downloads/ods2-test.ods";
	
	QString err;
	auto *book = ods::Book::FromFile(full_path, &err);
	
	if (!err.isEmpty()) {
		auto ba = err.toLocal8Bit();
		mtl_warn("%s", ba.data());
		return;
	}
	
	ods::AutoDelete<ods::Book*> ad(book);
	auto *spreadsheet = book->spreadsheet();
	auto *sheet = spreadsheet->GetSheet(0);
	
	{ /// B2 = row1 col1
		PrintValue(sheet, 1, 1);
	}
	
	{ /// F4 = row3, col5
		PrintValue(sheet, 3, 5);
	}
}`

**Comment by novalisek** [comment]
I am very sorry, I pulled and recompiled the library, but I forgot to copy new .dll files to .exe file directory :( It's working now

**Comment by f35f22fan** [comment]
Ok, glad the issue is sorted out.
